#ifndef CABALLEROSXD_H_INCLUDED
#define CABALLEROSXD_H_INCLUDED

void bronce()
{
    printf("IKKI FENIX\nYOGA CISNE\nSHUN ANDROMEDA\nSEIYA PEGASO\nSHIRUYU DRAGON\n");
}


#endif // CABALLEROSXD_H_INCLUDED
